# Generated by Django 3.2.2 on 2021-05-20 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0004_rename_doctor_patient_doctor_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='doctor_id',
            new_name='doctor',
        ),
    ]
