# Generated by Django 3.2.2 on 2021-05-22 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0006_fedi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fedi',
        ),
    ]
