# Generated by Django 3.2.2 on 2021-05-27 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0008_auto_20210522_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='Image_Consultation',
            field=models.FileField(upload_to='static/assets/ConsultationImages/'),
        ),
    ]
